name: Build and Deploy Android
on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --force

      - name: Bundle the app
        run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
     
      - name: Set Gradlew Permissions
        run: chmod +x android/gradlew
        
      - name: Doing Test
        run: npm test
        
      - name: Build application
        run: |
          cd ./android
          ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: android/app/build/outputs/apk/debug/app-debug.apk    
          
      # - uses: actions/upload-artifact@v3
      #   with:
      #    name: Build
      #    path: android/app/build/outputs/apk/debug/app-debug.apk    
  # deploy:
  #   needs: build
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
      
  #   steps:
  #     - name: Download Build Artifact
  #       uses: actions/download-artifact@v3
  #       id: download
  #       with:
  #         name: Build
  #         path: build              
  #     - run: zip -r build.zip build/
  #     - uses: ncipollo/release-action@v1
  #       with:
  #        artifacts: "build.zip"
  #        allowUpdates: true
         
      
  #     # - name: Upload application
  #     #   uses: actions/upload-artifact@v2
  #     #   id: create_release
  #     #   with:
  #     #    name: Build
  #     #    path: dist

  #     # - name: Download application
  #     #   uses: actions/download-artifact@v3
  #     #   id: download
  #     #   with:
  #     #    name: Build
  #     #    path: build

  #     - name: 'Echo download path'
  #       run: echo ${{steps.download.outputs.download-path}}
  #     - name: upload artifact to Firebase App Distribution
  #       uses: wzieba/Firebase-Distribution-Github-Action@v1
  #       with:
  #         appId: ${{secrets.FIREBASE_APP_ID}}
  #         serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
  #         groups: testers
  #         file: android/app/build/outputs/apk/debug/app-debug.apk
  #     - name: Send Email Notification
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 587
  #         username: mynulislamridoy
  #         password: ${{secrets.SMTP_PASSWORD}}
  #         subject: "Build and Deploy Notification"
  #         to: mynulislamridoy@gmail.com
  #         from: homeexercise8@gmail.com
  #         body: ${{steps.download.outputs.download_link}}



          
